import streamlit as st
import os
from dotenv import load_dotenv
import google.generativeai as genai
from PIL import Image
from fpdf import FPDF

# -------------------------------
# Load API Key
# -------------------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")

if not API_KEY:
    st.error("GOOGLE_API_KEY not found in .env file")
    st.stop()

# -------------------------------
# Configure Gemini
# -------------------------------
genai.configure(api_key=API_KEY)


MODEL_ID = "gemini-flash-latest" 

try:
    available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    if f"models/{MODEL_ID}" not in available_models and MODEL_ID not in available_models:
        st.warning(f"Model {MODEL_ID} not found. Using the first available model: {available_models[0]}")
        MODEL_ID = available_models[0]
    
    model = genai.GenerativeModel(MODEL_ID)
except Exception as e:
    st.error(f"Critical Error: Could not list or initialize models. Check your API Key. Error: {e}")
    st.stop()
# -------------------------------
# Helper Function: PDF Generation
# -------------------------------
def generate_pdf(text_content):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Civil Engineering Insight Report", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, "Generated by AI Structural Studio", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", size=11)
    # multi_cell automatically handles line breaks
    pdf.multi_cell(0, 8, text_content.encode('latin-1', 'replace').decode('latin-1'))
    return pdf.output()

# -------------------------------
# Streamlit UI
# -------------------------------
st.set_page_config(page_title="Civil Engineering Insight Studio", page_icon="🏗️")

st.header("🏗️ Civil Engineering Insight Studio")
st.markdown("Automated Structural Analysis, Safety Auditing, and Progress Documentation.")

uploaded_file = st.file_uploader("Upload Structure Image", type=["jpg", "jpeg", "png"])

# Enhanced Prompt with Safety Flag and Risk Score
analysis_prompt = (
    "You are a Senior Structural and Safety Engineer. Analyze the attached image and provide a report with:\n\n"
    "1. RISK ASSESSMENT SCORE: Rate from Low to High based on visible site conditions.\n"
    "2. STRUCTURAL TYPE & MATERIALS: Identify the type of structure and primary materials used.\n"
    "3. CONSTRUCTION PHASE: Describe the current progress stage.\n"
    "4. ⚠️ SAFETY ALERT FLAGS: Explicitly identify hazards like missing guardrails, "
    "unstable shoring, lack of PPE, or structural cracks.\n"
    "5. ENGINEERING INSIGHT: Describe load distribution or unique features."
)

if st.button("Generate Engineering Report"):
    if uploaded_file:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Site Photo", use_container_width=True)

        with st.spinner("AI is analyzing structural components and safety protocols..."):
            try:
                # Passing both prompt and image for multimodal analysis
                response = model.generate_content([analysis_prompt, image])
                report_text = response.text
                
                st.success("Analysis Complete!")
                st.subheader("📊 Engineering & Safety Report")
                st.markdown(report_text)

                # PDF Export Section
                st.divider()
                pdf_data = generate_pdf(report_text)
                st.download_button(
                    label="📥 Download Report as PDF",
                    data=bytes(pdf_data),
                    file_name="Engineering_Safety_Report.pdf",
                    mime="application/pdf"
                )

            except Exception as e:
                st.error(f"Error during analysis: {e}")
    else:
        st.warning("Please upload an image first.")

